name: Publish packages on NPM

on:
  workflow_dispatch:
    inputs:
      release:
        description: Version type to publish
        required: true
        type: choice
        options: [major, minor, patch]

env:
  version: ${{ inputs.release }}

jobs:
  publish:
    name: Publish packages
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: [18.x]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          registry-url: https://registry.npmjs.org
      
      - name: Set Git metadata
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
      
      - name: Install dependencies
        run: npm ci && npm run bootstrap
      
      - name: Set version to publish
        run: npm run version -- --yes --no-push ${{ env.version }}
      
      - name: Publish packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run publish -- from-package --yes
      
      - name: Push changes
        run: git push --force
